### ISSUE TITLE
Question about release workflow

### ISSUE THREAD

**Issue by kvmw** [crhntr/hello-release#3]
I was looking at `.github/workflows/release.yml` to understand the release steps better but it looks like this workflow has never been used to release this repo. 

The workflow supposed to push a new commit, base on the below command taken from the workflow, but I didn't see any commit with given message.  
`git commit -am "Create Release ${BOSH_RELEASE_VERSION}"`

Also, if I understood correctly, above commit would be after the release tag. which would be a little strange. one would expect that final commit to be tagged and released.

**Comment by crhntr** [comment]
I made mistakes in the action and workflow. When I build it, I was just trying to get tarballs to add to a tile. You're right this needs to be fixed.

**Comment by crhntr** [comment]
I think I fixed the workflow. Thanks for the report :)
